# Generated by Django 3.2.8 on 2021-10-28 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211028_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.rating'),
        ),
    ]
