# Generated by Django 3.2.8 on 2021-10-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='rating',
        ),
    ]
