# Generated by Django 3.2.8 on 2021-10-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_profile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
    ]
